### PR TITLE
Dot-Step

### PR DESCRIPTION
**Pull request by aszepieniec**
This PR:
 - Introduces two new instructions to the VM, `xxdotstep` and `xbdotstep` which executes one iteration of a typical dot product loop.
 - Adds state evolution logic and constraints for the new instructions.

T~~wo tasks remain before t~~his PR is ready:
 - [x] Update documentation.
 - [x] Fix failing test `constant_folding_processor_table` which detects duplicate nodes.

### CODE REVIEW

**Comment by jan-ferdinand** [comment]
I would also ask you to rebase & force-with-lease push to remove “wip” commits. :relieved:

**Comment by Sword-Smith** [comment]
I see you've moved the constant folding. It makes sense to do what you can on insertion, but I wanted to ask if we're still cathing as much as we did previously. I think we are but was wondering if you guys have more insight.

**Comment by jan-ferdinand** [comment]
We've thought it through and concluded that we are catching all the same cases as before. Moving it further ahead in the pipeline serves two benefits (and has no downsides as far as we can see):
- constant folding does not have to be called manually, and
- semantically duplicate nodes are detected earlier, removing the strange behavior that nodes with different IDs evaluate to the same expression.

**Comment by jan-ferdinand** [comment]
Thanks! Good work. :blush:

**Pull request merged**
